workflow:
  rules:
    # don't create a pipeline if its a commit pipeline, on a branch and that branch has open merge requests.
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - when: always

stages:
  - version
  - test

after_script:
  - echo "All done"

versioning:
  stage: version
  image: bitnami/git
  script:
    # Unshallowing ensures that 'git describe' works
    - git fetch --unshallow
    - echo VLBI_CWL_version=$(git describe --tags --always) >> versions.env
    - cat versions.env
  artifacts:
    reports:
      dotenv: versions.env

run_tests:
  stage: test
  image: astronrd/linc
  before_script:
    - pip3 install tox
  script:
    - tox -e py312
